"""Public notebook review cards; guides remain verbatim and PDFs untouched."""
from pathlib import Path
import chapter_content
import site_content
from urllib.parse import quote
def index(names):
    cards = []
    for name in names:
        stem = Path(name).stem
        topic = site_content.topic_for(name)
        chapter = chapter_content.CHAPTERS.get(stem, {})
        question = chapter.get('question', '')
        if not question.endswith('?'):
            question = f'What is the central physical idea in {stem}?'
        cards.append({'id': name, 'title': stem, 'topic': topic['title'] if topic else 'Other notes',
                      'question': question, 'url': chapter_content.chapter_url(name),
                      'pdf': '/pdfs/' + quote(name, safe='/'),
                      'guide': site_content.CATALOG.get('reading_guides', {}).get(stem, ''),
                      'contents': chapter.get('contents', [])})
    return cards


def page():
    return '''<div class="breadcrumbs"><a href="/notes/">Notes</a> / Daily review</div><header class="page-intro"><p class="eyebrow">A little, every day</p><h1>Return to an idea.</h1><p class="lead">Close the notebook for a moment. What can you bring back from memory?</p><p class="muted">Recall first. Check your handwriting. Leave with one clearer connection.</p></header>
    <section class="review-dashboard" aria-label="Daily review"><div class="review-stat"><strong data-review-due>—</strong><span>notebooks today</span></div><div class="review-stat"><strong data-review-today>—</strong><span>completed here</span></div><div class="review-stat"><strong data-review-next>—</strong><span>next daily set</span></div></section>
    <section id="daily-review" class="review-workspace"><div class="review-setup"><div><p class="kicker">Your daily practice</p><h2>Ten quiet minutes.</h2><p>Explain the physical picture, sketch a diagram, and connect it to another idea. Then check what you missed.</p></div><div><p class="kicker" data-review-date></p><p class="review-small">The same daily set for everyone · changes at 00:00 UTC.</p><button type="button" class="button" data-review-start disabled>Start today’s review →</button><a class="review-demo-link" href="/notes/review/?demo=1">Try a sample without saving progress ↗</a></div></div><ol class="review-daily-list" data-review-selection aria-label="Today’s notebooks"></ol><details class="review-upcoming"><summary>The next seven days</summary><ol data-review-upcoming></ol></details><p data-review-status role="status" aria-live="polite">Preparing your notebooks…</p>
    <article class="review-card" hidden aria-labelledby="review-title"><div class="review-card-top"><span data-review-count class="kicker"></span><span data-review-category class="kicker"></span></div><p class="review-source" data-review-notebook></p><h2 id="review-title"></h2><ol class="review-recall"><li>Explain the physical picture without looking.</li><li>Sketch the system or one equation, and say what it means.</li><li>Connect it to another concept you know.</li></ol><label for="review-response">Your recall · optional</label><textarea id="review-response" rows="3" placeholder="A few words, a sketch on paper, or explain it aloud…"></textarea><p class="review-small">Your response stays here during this session; it is not stored or sent.</p><button type="button" class="button" data-review-reveal>Check the notebook →</button>
    <section class="review-check" hidden><div class="section-head"><h3>Compare with the handwritten source</h3><a data-review-open target="_blank" rel="noopener">Open chapter ↗</a></div><div class="review-pdf-controls"><button type="button" data-review-prev aria-label="Previous handwritten page">←</button><span data-review-page role="status"></span><button type="button" data-review-forward aria-label="Next handwritten page">→</button><a data-review-pdf target="_blank" rel="noopener">Open original PDF ↗</a></div><div class="review-pdf-surface"><canvas role="img" aria-label="Handwritten notebook page"></canvas></div><details class="review-guide"><summary>Starting point · verbatim from Optimum</summary><div class="guide-verbatim" data-review-guide></div></details><p class="review-reflect">What did you miss? Correct one detail, then explain it once more without looking.</p><fieldset class="review-ratings"><legend>How well could you recall it?</legend><button type="button" data-review-grade="again"><strong>Couldn’t recall</strong><span data-interval="again"></span></button><button type="button" data-review-grade="shaky"><strong>Needed a hint</strong><span>Correct one detail</span></button><button type="button" data-review-grade="good"><strong>Recalled it</strong><span>Continue</span></button><button type="button" data-review-grade="easy"><strong>Could teach it</strong><span>Follow a connection</span></button></fieldset></section></article>
    <section class="review-finished" hidden><p class="kicker">A good place to stop</p><h2>Let the ideas settle.</h2><p data-review-finished></p><p>Come back tomorrow for the next shared set, or follow a connection now.</p><a class="button" href="/notes/">Browse the notebook →</a></section></section>
    <details class="review-method"><summary>How this practice works</summary><div class="prose"><p>Attempting to retrieve an idea before checking the source makes gaps visible. Returning on separate days gives you another chance to retrieve it after some forgetting. <a href="https://www.nature.com/articles/s44159-022-00089-1">Read about spacing and retrieval practice ↗</a></p><p>Everyone sees the same two notebooks each day: one focus notebook and a return to a notebook from three days earlier. The collection rotates through all available notebooks, alternating topics where possible. Small collections use the nearest distinct notebook. Dates change at midnight UTC so the selection is the same across devices and countries. New available notebooks join the rotation automatically.</p><p>Your self-assessment does not change the shared calendar. “Couldn’t recall” offers one additional attempt in this session; the other choices finish that notebook. Only today’s completion checkmarks are saved in this browser. No account is needed, and nothing is sent to a progress service. The sample does not save completion checkmarks. Notebook text and Optimum guides remain unchanged.</p></div></details><noscript><p>Daily review needs JavaScript. You can still <a href="/notes/">browse and read the notebooks</a>.</p></noscript>'''
